### ISSUE TITLE
McKellarMuscleData

### ISSUE THREAD

**Issue by SaskiaFreytag** [pachterlab/SFEData#1]
Hi, 

I have tried to follow the tutorial on your awesome looking Voyager package but I run into a problem with this package. When trying to download the McKellar Muscle data, I obtained the following error:

```
library(SFEData)
sfe <- McKellarMuscleData("full")
```

This gives the following error message:

```
snapshotDate(): 2021-10-19
Error: EH7560 added after current Hub snapshot date.
  added: 2022-07-08
  snapshote date: 2021-10-19
```

Any clues what the issue may be?

Cheers,

Saskia

**Comment by lambdamoses** [comment]
You must use the devel version of Bioconductor to eliminate this error.
